import streamlit as st

st.set_page_config(
    page_title="Hello World",
    page_icon=":mortar_board:",
)

st.write("# :mortar_board: Predict Graduation Midterms Project! :female-student: ")

st.sidebar.success("Select a page.")

st.markdown(
    """
    This is the web-service for #mlzoomcamp's midterms, using StreamLit
    - You can learn more about StreamLit at [streamlit.io](https://streamlit.io)
    - Go to the [Project's Github repo](https://github.com/ellacharmed/mlzoomcamp-midterms-predict-graduation) for this project to look at its source code
    - The Dataset is generated by Royce Kimmons at this [link](http://roycekimmons.com/tools/generated_data/graduation_rate)
    - Provide feedback in the Issues tab on Github!
    - Or, hit me up on [Slack](https://datatalks-club.slack.com/team/U057GC2CG4W).
    
    ### Concepts
    This project is to showcase following concepts based on weeks1-6 of the [Machine Learning Zoomcamp](https://github.com/DataTalksClub/machine-learning-zoomcamp) run by [@DataTalksClub](https://twitter.com/DataTalksClub)
    
    - :question: how to frame our problem statement so we select the right `target`
    - :chart_with_upwards_trend: exploratory data analysis
      - what charts to show what trends?
    - :dart: modeling selection
      - which estimator is best suited to the problem we want to solve?
    - :key: model tuning
      - cross-validation and kfolds to split data
      - hyperparameter tuning
    - :link: evaluation
      - what metrics suits best for what kind of problem statement?
    - deployment involving
      - :snake: turning our code into python scripts
      - :spider_web: a web service
      - :whale2: docker
      - :battery: environment management
      - :electric_plug: dependency management
    
    Additional topics not covered but we were encouraged to learn for the project is
    anything that helps in an End-to-End Machine Learning Deployment
      
"""
)
